apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: b8ih75ecm-java-quarkus-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/b8ih75ecm-java-quarkus-gitops